apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dataenablement-api
  title: Dataenablement Api
  description: Dataenablement APIs
  links:
    - title: Facility
      url: https://gw1.qa.api.volvocars.biz/workplace/facilities
    - title: Documentation
      url: https://volvocargroup.visualstudio.com/Corporate%20Worklife/_wiki/wikis/Corporate%20Worklife/23325/App-Facility
  annotations:
    github.com/project-slug: dgovind1/dataenablement-api
spec:
  type: service
  owner: dataenablement@volvocars.com
  system: dataenablement-api
  lifecycle: experimental
