apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dataenablement-api
  title: Dataenablement Api
  description: Dataenablement
  annotations:
    github.com/project-slug: dgovind1/dataenablement-api
spec:
  type: service
  owner: subzero
  lifecycle: experimental
